### ISSUE TITLE
AkdKey and Values should be standardized

### ISSUE THREAD

**Issue by slawlor** [novifinancial/akd#104]
The types ```AkdKey``` and ```Values``` should be standardized in their naming, definition and usage. They're a little hazard at the moment. (one is ```Akd...``` the other is just ```...```, etc).

Additionally we should migrate to binary (```&[u8]```) instead of strings to save on storage sizing for at least the value, if not the key also. All our operations are done on the binary values, so it's just for readability that it's strings. This will induce data-layer changes in the ```akd_mysql``` crate as well, as we'll be changing data-layer types.

**Comment by eozturk1** [comment]
SEEMless uses the terms `Label` and `Value` for key and value, respectively. 

My preference would be the following change: `AkdKey ` -> `Label` and  `Values` -> `Value`. This also side-steps the issue of using "key" to name the labels while storing (crypto) keys as values.

Other suggestions?

**Comment by eozturk1** [comment]
To prevent the confusion with `NodeLabel`s, we could use `AkdLabel` and `AkdValue`?

**Comment by slawlor** [comment]
```AkdLabel``` and ```AkdValue``` are ok to me. @kevinlewi and opinion here?

Additionally instead of ```&[u8]``` which is size unknown at compile time, we should probably look at ```Vec<u8>``` since Rust won't allow unsized as a struct property.

**Comment by kevinlewi** [comment]
I like the suggested naming conventions! Yes, let's go with `AkdKey`, `AkdValue`, and having them be `Vec<u8>`

**Comment by slawlor** [comment]
If you haven't already started on this @eozturk1 can I take it back for a camper? We have a new camper who this is a great intro-level task for them (and get's them into OSS).

Thanks!

**Comment by slawlor** [comment]
This appears completed. Closing issue
