### ISSUE TITLE
Creating and storing persistent VRF public and secret keys.

### ISSUE THREAD

**Issue by Jasleen1** [novifinancial/akd#124]
Now that we have a PR implementing the VRFs, we should find a way to securely generate, store and access the VRF secret key and to publish a VRF public key. 

The `vrf` crate could probably support key generation but still it needs to be stored somewhere.

**Comment by slawlor** [comment]
Update: Will be moved to a trait which will be implemented by users of the library (since key storage varies widely by implementation constraints)

**Comment by eozturk1** [comment]
Github offers [encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) that can be used with [Github actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions). Did you mean a solution for key generation/storage/access for the long term?

**Comment by slawlor** [comment]
> Github offers [encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) that can be used with [Github actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions). Did you mean a solution for key generation/storage/access for the long term?

Yeah no, it's more where the VRF key would live which is specific to each deployment (my deployment may not want to talk to github, or even have network access, etc). It's better as a trait which is left to whoever is going to utilize the lib to implement where to get the VRF key from.
