### ISSUE TITLE
Improve debugging by adding error contexts

### ISSUE THREAD

**Issue by eozturk1** [novifinancial/akd#157]
We have errors that **only** include the error string in the error. When these errors surface up, they don't have any context on where and why they occurred (e.g., a MySQL error). We should improve these by adding

- More context to the errors, e.g., `GetData` error in `batch_get` should mention that the operation was batch get.
- Stack trace info.  --> Since the stack trace leading to the error is cleared up when the error is caught, we lose this info.
- Line numbers and file names when the error occurred.

**Comment by slawlor** [comment]
A good point to check into on this might be the `log` crate, there is already a capturing which occurs with each macro call (e.g. `debug!(...)`) that is capturing a lot of this information. You can check our own log implementations, but we're capturing exactly this kind of info (file, line, thread, etc).

**Comment by eozturk1** [comment]
The logs by the `log` crate are not displayed (except `println!`). We need a logger implementation other than the `log` crate -- maybe [env_logger](https://crates.io/crates/env_logger). And [initialize](https://stackoverflow.com/questions/30177845/how-to-initialize-the-logger-for-integration-tests) it. Then we can get those logs.

**Comment by slawlor** [comment]
Ah I meant looking at how they capture the file, line number, method, etc. Not actually relying on it, sorry!

**Comment by slawlor** [comment]
So I think logging is going to be the way to go here. I was looking into how this would be implemented, but we would need to redefine the error structures we pass around to also collect a "context" object and when an error is to be returned, append the context about module,line,file,etc. This means modifying every location where an error response is generated, and kind of goes against the "spirit" of Rust's `Result<_,_>` type (from what I'm reading).

We can do it, but I think utilizing the log crate more heavily is going to make more sense here. I did do a large cleanup of the error types and how they're propagated around to make more sense of them, but no context as of yet.

**Comment by eozturk1** [comment]
Yeah, +1 on using the log crate. With proper context and unique error messages, we don't need the file/line to be included. I guess the initial issue we should focus on is actually getting the logs using env_logger. Otherwise, if they aren't `println!` I can't see any logs.

**Comment by slawlor** [comment]
> Yeah, +1 on using the log crate. With proper context and unique error messages, we don't need the file/line to be included. I guess the initial issue we should focus on is actually getting the logs using env_logger. Otherwise, if they aren't `println!` I can't see any logs.

Qq: Where are you seeing or not-seeing the logs? What are you looking at for log messages? The unit tests I guess? We might need to write a wrapper to initialize the log env in tests such that failures will show the log info

**Comment by eozturk1** [comment]
Unit tests. Mainly the console. It seems #168 does the initialization.
