### ISSUE TITLE
Optimize for size-bounded cache

### ISSUE THREAD

**Issue by eozturk1** [novifinancial/akd#164]
Currently we have a [timed cache](https://github.com/novifinancial/akd/blob/aa96aee67c536b495353503dd6e1170082abd940/akd/src/storage/timed_cache.rs) with unbounded space. Lifetime of the items in the cache is 30 seconds. 

With the growing tree size and increasing number of requested operations (e.g., lookups), the size of the cache may become a limiting factor for how many operations we can handle. In that case, we will need to manage the cache more effectively. 

To this end, some initial ideas are:
- Varying expiration times for nodes depending on their use frequency.
- Prioritize some (e.g., most used?) nodes during `batch_get` operations.

cc @afterdusk

**Comment by kevinlewi** [comment]
I believe this was resolved by #269, @eozturk1 can you confirm?

**Comment by eozturk1** [comment]
> Adding support for memory pressure processing to limit the cache size based on the memory pressure on the system

Yes!
