### ISSUE TITLE
Adding domain separation for tree hashing

### ISSUE THREAD

**Issue by kevinlewi** [novifinancial/akd#172]
We need to add domain separation for hashing of internal nodes / leaves in the tree. Right now, if we are doing something like H(payload), we should instead do something like H("AKD-v0.4" || nonce || payload), where a per-tree nonce is also stored somewhere.

cc: @Jasleen1

**Comment by kevinlewi** [comment]
After some discussion with @slawlor, let's leave out the nonce in the computation and just stick with the fixed string for domain separation. i.e.: H("AKD-v0.4" || payload)

**Comment by eozturk1** [comment]
What is domain separation?

**Comment by kevinlewi** [comment]
@eozturk1 this just refers to adding a fixed string specific to this application into the hash computation. That way, hashing this value won't "collide" or interfere with other applications that might hash the same input.

**Comment by kevinlewi** [comment]
I see, good point. Yes, we can omit hardcoding the version into these strings, that should be fine!

**Comment by kevinlewi** [comment]
Closing this off since the VRF private/public key already ensures that the hashes generated by AKD are not going to collide with other hashes used elsewhere.
