### ISSUE TITLE
Key history proofs should check that previous versions were retired when they should be

### ISSUE THREAD

**Issue by Jasleen1** [novifinancial/akd#222]
https://github.com/novifinancial/akd/blob/89da4370094e46234924e1efedfcb01633cfb11c/akd/src/client.rs#L347 includes a check for membership of the stale label but do not check that this label was inserted when the newer version was added. This is a fairly minor change adding lines such as:

```
if !(H::merge_with_int(H::hash(&crate::EMPTY_VALUE).as_bytes(), proof.epoch)
                    == previous_val_stale_at_ep.hash_val) {
      // Throw error 
}
```

**Comment by kevinlewi** [comment]
Closed by https://github.com/novifinancial/akd/pull/224
