### ISSUE TITLE
Differentiate between private and non-private mode

### ISSUE THREAD

**Issue by Jasleen1** [novifinancial/akd#64]
Some applications may be amenable to a lower privacy level, such as certificate transparency. For these examples, we do not need a VRF and can thus be more efficient. We should allow both private and non-private modes for this crate. Perhaps using features.

**Comment by slawlor** [comment]
This is completed, there is a feature `vrf` now which is on-by-default, but can be disabled on the `akd` crate with

```
cargo build --package akd --no-default-features
```

Relevant PR linked to issue
